### ISSUE TITLE
isPaused() and isStopped() don't work

### ISSUE THREAD

**Issue by h4yn0nnym0u5e** [FrankBoesing/Teensy-WavePlayer#7]
Declared as `bool isXXXXed(void)` but defined as `inline bool isXXXXed(void)`, so linker fails

**Comment by FrankBoesing** [comment]
fixed with 9123eef#diff-857cf77a0d8d0353818b0d4f5d233e9275588b84862ab1b34396db4b887b5262

Thank you!
