### ISSUE TITLE
Not an issue, more a question : pitch shifting ?

### ISSUE THREAD

**Issue by localhero44** [FrankBoesing/Teensy-WavePlayer#9]
Hi Frank,
Would it be possible to add pitch shifting for sample playing ?
I would like to build a hardware sample player which receives the note to be played by MIDI.
Multiple samples at once of course for chords.
Regards

**Comment by FrankBoesing** [comment]
Yes, you (->not me) can add it. But the better place is the audio library. There are some solutions for this in the forum.
